name: Api

on:
  push:
    paths:
    - 'api/**'
    - 'cdk/lib/api.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: python -m pytest tests/ -v
      env:
        AWS_DEFAULT_REGION: "us-east-1"
        TABLE_NAME: table
        SITE_DOMAIN: domain
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    defaults:
      run:
        working-directory: cdk
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g cdk
    - run: npm ci
    - run: mkdir -p ../site/out
    - run: cdk synth -c domain=$DOMAIN MyApi
    - run: cdk diff -c domain=$DOMAIN MyApi
    - run: cdk deploy -c domain=$DOMAIN MyApi --force
