name: CDK deploy Api Static Site

on:
  push:
    branches:
      - master
    paths:
    - 'site/**'
    - 'cdk/lib/static-site.ts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGIONY }}
    - uses: actions/download-artifact@v2
      with:
        name: nextjs-out
        path: site/out/
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd cdk
    - run: npm install -g cdk
    - run: npm ci
    - run: cdk synth -c domain=$DOMAIN MyApi
    - run: cdk deploy -c domain=$DOMAIN MyApi
