name: Nextjs build

on:
  pull_request:
    paths:
    - 'site/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
    - uses: actions/upload-artifact@v2
      with:
        name: nextjs-out
        path: site/out/
